services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0 # Date-based release
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"

    environment:
      TZ: "America/Los_Angeles"
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1" # cloudflare DNS
      DNSSEC: "true"
      WEBTHEME: "default-dark"
      DNSMASQ_LISTENING: "all" # need to listen on all interfaces as we are on a docker network
      PIHOLE_DOMAIN: "pihole.birki.io" # set domain name here or comment out to use default
      WEBPASSWORD_FILE: /run/secrets/WEBPASSWORD_FILE
    secrets:
       - WEBPASSWORD_FILE

    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"

    # Required if you are using Pi-hole as your DHCP server, else not needed
    # cap_add:
    # - NET_ADMIN

    restart: unless-stopped

secrets:
  WEBPASSWORD_FILE:
    file: WEBPASSWORD_FILE.txt
