services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.09 # Date-based release that can receive bugfix updates
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8000:80/tcp"

    environment:
      TZ: "America/Denver"
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
      DNSSEC: "true"
      WEBTHEME: "default-dark"
      DNSMASQ_LISTENING: "local"
      PIHOLE_DOMAIN: "pihole.birki.net"
      WEBPASSWORD_FILE: /run/secrets/WEBPASSWORD_FILE
    secrets:
       - WEBPASSWORD_FILE

    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"

    # Required if you are using Pi-hole as your DHCP server, else not needed
    # cap_add:
    # - NET_ADMIN

    restart: unless-stopped

secrets:
  WEBPASSWORD_FILE:
    file: WEBPASSWORD_FILE.txt
