name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deployment-check:
    runs-on: ubuntu-latest
    outputs: # set outputs for use in downstream jobs
      continue: ${{ steps.deployment-check.outputs.continue }}

    steps:
      # https://github.com/github/branch-deploy/blob/d3c24bd92505e623615b75ffdfac5ed5259adbdb/docs/merge-commit-strategy.md
      - name: deployment check
        uses: github/branch-deploy@v9
        id: deployment-check
        with:
          merge_deploy_mode: "true"
          environment: production

  deploy:
    if: ${{ needs.deployment-check.outputs.continue == 'true' }}
    needs: deployment-check
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      # start an in_progress deployment with the gh cli
      - name: start deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEPLOYMENT_RESPONSE=$(echo '{"ref":"main","environment":"production","required_contexts":[],"description":"main branch deployment"}' | gh api repos/:owner/:repo/deployments -X POST --input -)
          DEPLOYMENT_ID=$(echo $DEPLOYMENT_RESPONSE | jq .id)
          echo '{"state":"in_progress"}' | gh api repos/:owner/:repo/deployments/$DEPLOYMENT_ID/statuses -X POST --input -
