name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0

      - name: GH Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # pin@v0.1.14
